name: UI-tests
run-name: UI-tests

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 5
      matrix:
        java_version: [23]
    runs-on: ubuntu-latest
    name: ${{ join(matrix.*, '_') }}
    env:
      MATRIX_JOB_NAME: ${{ join(matrix.*, '_') }}

    steps:
      - name: "[Prepare] Checkout"
        uses: actions/checkout@v4

      - name: "[Prepare] Setup JDK 23"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}

      - name: "[Test] Execute"
        id: test_execution
        run: |
          ./gradlew clean webTests allureReport

      - if: success() || failure()
        name: "[Report] JUnit report"
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: JUnit ${{ env.MATRIX_JOB_NAME }}
          report_paths: build/reports/test/TEST-*.xml

      - if: steps.test_execution.conclusion == 'failure'
        name: "[Artifact] Gradle result"
        uses: actions/upload-artifact@v4
        with:
          name: report-gradle-${{ env.MATRIX_JOB_NAME }}
          path: build/reports/tests/test

      - if: always()
        name: "[Artifact] Allure report"
        uses: actions/upload-artifact@v4
        with:
          name: report-allure-${{ env.MATRIX_JOB_NAME }}
          path: build/allure/allureReport